version: '3.8'

services:
  # 1. The Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. The Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 3. The Backend API
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=url_shortener
      - JWT_SECRET=super_secret_jwt_key_123
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  # 4. The React Frontend <--- NEW
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: